version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=4096"
    restart: unless-stopped